name: PlatformIO CI

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
        
      - name: Run Water Level Controller Test
        run: pio test -e test_native -f "test_native_water_level_controller.c"

      - name: Run Communication Controller Test
        run: pio test -e test_native -f "test_native_communication_controller.c"

      - name: Run Display Controller Test
        run: pio test -e test_native -f "test_native_display_controller.c"

      - name: Run EEPROM Controller Test
        run: pio test -e test_native -f "test_native_eeprom.controller.c"

      - name: Run Humidity Temperature Controller Test
        run: pio test -e test_native -f "test_native_humidity_temperature_controller.c"

      - name: Run Moisture Controller Test
        run: pio test -e test_native -f "test_native_moisture_controller.c"

      - name: Run Pump Controller Test
        run: pio test -e test_native -f "test_native_pump_controller.c"

      - name: Run UV Sensor Controller Test
        run: pio test -e test_native -f "test_native_uvsensor_controller.c"
