name: Arduino CI

on:
  push:
    branches:
      - '*'
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

  test_native:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v3

    - name: Set up Unity
      run: |
        mkdir -p $HOME/unity
        curl -Ls https://github.com/ThrowTheSwitch/Unity/archive/refs/tags/v2.5.2.tar.gz | tar xz -C $HOME/unity --strip-components=1
        export PATH="$HOME/unity/extras/fixture/src:$PATH"

    - name: Build and Test
      run: |
        g++ -o test_native -DWINDOWS_TEST=1 -DNATIVE_TEST=1 -Ilib/controllers -Ilib/drivers test_native.cpp
        ./test_native
